apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-metric-samples
  labels:
    app.kubernetes.io/name: mq-metric-samples
    app.kubernetes.io/instance: mq-metric-samples
    app: mq-metric-samples
    app.kubernetes.io/part-of: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mq-metric-samples
      app.kubernetes.io/instance: mq-metric-samples
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mq-metric-samples
        app.kubernetes.io/instance: mq-metric-samples
    spec:
      serviceAccountName: mq-metric-samples
      volumes:
      containers:
        - name: mq-metric-samples
          image: image-registry.openshift-image-registry.svc:5000/ci/mq-metric-samples:v5.3.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          envFrom:
            - configMapRef:
                name: mq-metric-samples
            - secretRef:
                name: mq-metric-samples
          resources:
            null
